import { Head, useForm } from '@inertiajs/react';
import HendhysLayout from '@/Layouts/HendhysLayout';
import Icon from '@/Components/Icon';
const route = window.route;
export default function ReturnsCreate({ products, units }) {
    const { data, setData, post, processing, errors } = useForm({ date: new Date().toISOString().slice(0, 10), notes: '', items: [{ product_id: '', quantity: 1, unit_id: '', condition: 'rusak' }] });
    const addItem = () => setData('items', [...data.items, { product_id: '', quantity: 1, unit_id: '', condition: 'rusak' }]);
    const removeItem = (i) => setData('items', data.items.filter((_, idx) => idx !== i));
    const updateItem = (i, field, value) => { const items = [...data.items]; items[i][field] = value; if (field === 'product_id') { const p = products.find(pr => pr.id == value); if (p) items[i].unit_id = p.unit_id; } setData('items', items); };
    const submit = (e) => { e.preventDefault(); post(route('hendhys.returns.store')); };
    return (
        <HendhysLayout pageTitle="Buat Return ke Produksi">
            <Head title="Buat Return" />
            <form onSubmit={submit} className="mx-auto max-w-4xl space-y-6">
                <h2 className="text-2xl font-bold text-gray-800 dark:text-white/90">Return Barang ke Produksi</h2>
                <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs space-y-4 dark:border-gray-800 dark:bg-white/[0.03]">
                    <div className="grid grid-cols-1 gap-4 md:grid-cols-2"><div><label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Tanggal</label><input type="date" value={data.date} onChange={(e) => setData('date', e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 bg-white dark:bg-gray-800 dark:text-white focus:border-amber-500 focus:ring-amber-500" /></div><div><label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Catatan</label><input type="text" value={data.notes} onChange={(e) => setData('notes', e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 bg-white dark:bg-gray-800 dark:text-white focus:border-amber-500 focus:ring-amber-500" /></div></div>
                    <div className="pt-4"><h3 className="font-semibold text-gray-800 mb-3 dark:text-white/90">Item Return</h3>{data.items.map((item, i) => (<div key={i} className="mb-3 flex flex-wrap items-end gap-3 rounded-lg border border-gray-100 bg-gray-50 p-3 dark:border-gray-800 dark:bg-white/[0.02]"><div className="min-w-[180px] flex-1"><label className="text-xs text-gray-500 dark:text-gray-400">Produk</label><select value={item.product_id} onChange={(e) => updateItem(i, 'product_id', e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 bg-white dark:bg-gray-800 dark:text-white focus:border-amber-500 focus:ring-amber-500"><option value="">-- Pilih --</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="w-24"><label className="text-xs text-gray-500 dark:text-gray-400">Qty</label><input type="number" min="1" value={item.quantity} onChange={(e) => updateItem(i, 'quantity', e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 bg-white dark:bg-gray-800 dark:text-white focus:border-amber-500 focus:ring-amber-500" /></div><div className="w-28"><label className="text-xs text-gray-500 dark:text-gray-400">Satuan</label><select value={item.unit_id} onChange={(e) => updateItem(i, 'unit_id', e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 bg-white dark:bg-gray-800 dark:text-white focus:border-amber-500 focus:ring-amber-500">{units.map((u) => <option key={u.id} value={u.id}>{u.abbreviation}</option>)}</select></div><div className="w-28"><label className="text-xs text-gray-500 dark:text-gray-400">Kondisi</label><select value={item.condition} onChange={(e) => updateItem(i, 'condition', e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 bg-white dark:bg-gray-800 dark:text-white focus:border-amber-500 focus:ring-amber-500"><option value="rusak">Rusak</option><option value="basi">Basi</option><option value="lainnya">Lainnya</option></select></div>{data.items.length > 1 && <button type="button" onClick={() => removeItem(i)} className="rounded-lg bg-red-50 p-2 text-red-500 hover:bg-red-100 dark:bg-red-500/10 dark:text-red-400"><Icon name="delete" className="text-[20px]" /></button>}</div>))}<button type="button" onClick={addItem} className="mt-2 inline-flex items-center gap-1 rounded-lg border border-dashed border-gray-300 px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-50 dark:border-gray-700 bg-white dark:bg-gray-800 dark:text-white focus:border-amber-500 focus:ring-amber-500"><Icon name="add" className="text-[18px]" /> Tambah</button></div>
                </div>
                <div className="flex justify-end gap-3"><button type="button" onClick={() => window.history.back()} className="rounded-2xl border border-gray-200 bg-white px-6 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:bg-white/[0.01] dark:border-gray-800 dark:bg-white/[0.03]">Batal</button><button type="submit" disabled={processing} className="rounded-xl bg-amber-600 px-8 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-amber-700 disabled:opacity-50">{processing ? 'Mengirim...' : 'Kirim Return'}</button></div>
            </form>
        </HendhysLayout>
    );
}
